package com.dcits.depsit.service.utils;

import com.dcits.depsit.entity.RbBusTranJnl;
import com.dcits.depsit.entity.RbBusTranJnlExample;
import com.dcits.depsit.facade.eo.RbBusTranJnlEO;
import com.dcits.depsit.enums.TranType;
import com.dcits.depsit.enums.SourceType;
import com.dcits.depsit.enums.SourceModule;
import com.dcits.depsit.enums.IssCountry;
import com.dcits.depsit.enums.Ccy;
import com.dcits.depsit.enums.State;
import com.dcits.depsit.enums.TranType;
import com.dcits.depsit.enums.MediumFlag;
import com.dcits.depsit.enums.FromRateFlag;
import com.dcits.depsit.enums.AcctCcy;
import com.dcits.depsit.enums.FromRateFlag;
import com.dcits.depsit.enums.RateType;
import com.dcits.depsit.enums.AcctSetType;
import com.dcits.depsit.enums.SourceType;
import com.dcits.depsit.enums.DocumentType;
import com.dcits.depsit.enums.DocumentType;
import com.dcits.depsit.enums.ToId;
import com.dcits.depsit.enums.BalType;
import com.dcits.depsit.enums.AcctStatus;
import com.dcits.depsit.enums.RcrRcdInd;
import com.dcits.depsit.enums.ApprIndicator;
import com.dcits.depsit.enums.DocumentType;
import com.dcits.depsit.enums.TranBranch;
import com.dcits.depsit.enums.State;
import com.dcits.depsit.enums.SourceModule;
import com.dcits.depsit.enums.ProfitCenter;
import com.dcits.depsit.enums.IssCountry;
import com.dcits.depsit.enums.TranMethod;
import com.dcits.depsit.enums.IssCountry;
import com.dcits.depsit.enums.CashItem;
import com.dcits.depsit.enums.TranBranch;
import com.dcits.depsit.enums.ToId;
import com.dcits.depsit.enums.IssCountry;
import com.dcits.depsit.enums.AutoReversalFlag;
import com.dcits.depsit.enums.AcctClass;
import com.dcits.depsit.enums.TranBranch;
import com.dcits.depsit.enums.IssCountry;
import com.dcits.depsit.enums.Ccy;
import com.dcits.depsit.enums.IntCalcAmtType;
import com.dcits.depsit.enums.ClientType;
import com.dcits.depsit.enums.AcctTranFlag;
import com.dcits.depsit.enums.AmtCalcType;
import com.dcits.depsit.enums.AcctCcy;
import com.dcits.depsit.enums.AccountingStatus;
import com.dcits.depsit.enums.Ccy;
import com.dcits.depsit.enums.RemainTerm;
import com.dcits.depsit.enums.Ccy;
import com.dcits.depsit.enums.MediumType;
import com.dcits.depsit.enums.CrDrInd;
import com.dcits.depsit.enums.TranStatus;
import com.dcits.depsit.enums.DocType;
import com.dcits.depsit.enums.WithdrawalType;

public final class RbBusTranJnlValueUtil {
    private RbBusTranJnlValueUtil() {
    }

    public static RbBusTranJnlEO entityToEo(RbBusTranJnl entity) {
        if (entity == null) {
            return null;
        }
        RbBusTranJnlEO eo = new RbBusTranJnlEO();
        eo.setCommissionClientTel(entity.getCommissionClientTel());
        eo.setReversalDate(entity.getReversalDate());
        eo.setReversalTranType(TranType.byValue(entity.getReversalTranType()));
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setFhSeqNo(entity.getFhSeqNo());
        eo.setOrigSystem(SourceModule.byValue(entity.getOrigSystem()));
        eo.setOthDocumentId(entity.getOthDocumentId());
        eo.setPreviousBalAmt(entity.getPreviousBalAmt());
        eo.setTranCountry(IssCountry.byValue(entity.getTranCountry()));
        eo.setLastUpdTimestamp(entity.getLastUpdTimestamp());
        eo.setTranNote(entity.getTranNote());
        eo.setContraAcctCcy(Ccy.byValue(entity.getContraAcctCcy()));
        eo.setLimitRefList(entity.getLimitRefList());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setReversalFlag(entity.getReversalFlag());
        eo.setCashFromCode(entity.getCashFromCode());
        eo.setOthReference(entity.getOthReference());
        eo.setOthRealBranchRegionCode(State.byValue(entity.getOthRealBranchRegionCode()));
        eo.setTranType(TranType.byValue(entity.getTranType()));
        eo.setOthRealTranName(entity.getOthRealTranName());
        eo.setVoucherNo(entity.getVoucherNo());
        eo.setReaccountCd(entity.getReaccountCd());
        eo.setPrimaryTranSeqNo(entity.getPrimaryTranSeqNo());
        eo.setBaseCcyAmountOne(entity.getBaseCcyAmountOne());
        eo.setMediumFlag(MediumFlag.byValue(entity.getMediumFlag()));
        eo.setOvToAmount(entity.getOvToAmount());
        eo.setFromRateFlag(FromRateFlag.byValue(entity.getFromRateFlag()));
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setToRateFlag(FromRateFlag.byValue(entity.getToRateFlag()));
        eo.setNarrative(entity.getNarrative());
        eo.setOthRealBaseAcctNo(entity.getOthRealBaseAcctNo());
        eo.setOthAcctDesc(entity.getOthAcctDesc());
        eo.setCommissionClientName(entity.getCommissionClientName());
        eo.setPrintIndicator(entity.getPrintIndicator());
        eo.setIsFinSubAcct(entity.getIsFinSubAcct());
        eo.setActualBal(entity.getActualBal());
        eo.setCrossRate(entity.getCrossRate());
        eo.setEventType(entity.getEventType());
        eo.setContraEquivAmt(entity.getContraEquivAmt());
        eo.setRateType(RateType.byValue(entity.getRateType()));
        eo.setEffectDate(entity.getEffectDate());
        eo.setAcctSetType(AcctSetType.byValue(entity.getAcctSetType()));
        eo.setChannelSeqNo(entity.getChannelSeqNo());
        eo.setApprUserId(entity.getApprUserId());
        eo.setTackOverCcyRateTwo(entity.getTackOverCcyRateTwo());
        eo.setChannel(SourceType.byValue(entity.getChannel()));
        eo.setOthDocumentType(DocumentType.byValue(entity.getOthDocumentType()));
        eo.setOthRealDocumentType(DocumentType.byValue(entity.getOthRealDocumentType()));
        eo.setLoanProdNo(entity.getLoanProdNo());
        eo.setToId(ToId.byValue(entity.getToId()));
        eo.setCustRate(entity.getCustRate());
        eo.setBalType(BalType.byValue(entity.getBalType()));
        eo.setSubAcctNo(entity.getSubAcctNo());
        eo.setBusSeqNo(entity.getBusSeqNo());
        eo.setAcctStatus(AcctStatus.byValue(entity.getAcctStatus()));
        eo.setRcrRcdInd(RcrRcdInd.byValue(entity.getRcrRcdInd()));
        eo.setExchangeTranCode(entity.getExchangeTranCode());
        eo.setClientName(entity.getClientName());
        eo.setServCharge(entity.getServCharge());
        eo.setAcctSeqNo(entity.getAcctSeqNo());
        eo.setApprIndicator(ApprIndicator.byValue(entity.getApprIndicator()));
        eo.setDocumentType(DocumentType.byValue(entity.getDocumentType()));
        eo.setAcctBranch(TranBranch.byValue(entity.getAcctBranch()));
        eo.setOthTranName(entity.getOthTranName());
        eo.setIsCommTran(entity.getIsCommTran());
        eo.setClientNo(entity.getClientNo());
        eo.setBaseCcyAmountTwo(entity.getBaseCcyAmountTwo());
        eo.setAcctRealFlag(entity.getAcctRealFlag());
        eo.setOthBranchRegionalismCode(State.byValue(entity.getOthBranchRegionalismCode()));
        eo.setFromAmount(entity.getFromAmount());
        eo.setSourceModule(SourceModule.byValue(entity.getSourceModule()));
        eo.setToXrate(entity.getToXrate());
        eo.setProfitCenter(ProfitCenter.byValue(entity.getProfitCenter()));
        eo.setCashToCountry(IssCountry.byValue(entity.getCashToCountry()));
        eo.setBankSeqNo(entity.getBankSeqNo());
        eo.setCashToCode(entity.getCashToCode());
        eo.setPrimaryEventType(entity.getPrimaryEventType());
        eo.setTranMethod(TranMethod.byValue(entity.getTranMethod()));
        eo.setLender(entity.getLender());
        eo.setProgramId(entity.getProgramId());
        eo.setCashFromCountry(IssCountry.byValue(entity.getCashFromCountry()));
        eo.setOthRealProdNo(entity.getOthRealProdNo());
        eo.setPrintCnt(entity.getPrintCnt());
        eo.setDealCode(entity.getDealCode());
        eo.setProdNo(entity.getProdNo());
        eo.setOthBankCode(entity.getOthBankCode());
        eo.setOthBaseAcctNo(entity.getOthBaseAcctNo());
        eo.setCashItem(CashItem.byValue(entity.getCashItem()));
        eo.setBatchNo(entity.getBatchNo());
        eo.setChannelDate(entity.getChannelDate());
        eo.setBillNo(entity.getBillNo());
        eo.setSeqNo(entity.getSeqNo());
        eo.setReceiptNo(entity.getReceiptNo());
        eo.setOvCrossRate(entity.getOvCrossRate());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setOthBranch(TranBranch.byValue(entity.getOthBranch()));
        eo.setReference(entity.getReference());
        eo.setQuoteType(ToId.byValue(entity.getQuoteType()));
        eo.setCashSourceCountry(IssCountry.byValue(entity.getCashSourceCountry()));
        eo.setAutoReversalFlag(AutoReversalFlag.byValue(entity.getAutoReversalFlag()));
        eo.setTranAmt(entity.getTranAmt());
        eo.setGlPostedFlag(entity.getGlPostedFlag());
        eo.setAcctClass(AcctClass.byValue(entity.getAcctClass()));
        eo.setPbkUpdFlag(entity.getPbkUpdFlag());
        eo.setGlNo(entity.getGlNo());
        eo.setActualBalAmtFin(entity.getActualBalAmtFin());
        eo.setTranBranch(TranBranch.byValue(entity.getTranBranch()));
        eo.setPrefix(entity.getPrefix());
        eo.setCashUsePlaceCode(IssCountry.byValue(entity.getCashUsePlaceCode()));
        eo.setSettlementDate(entity.getSettlementDate());
        eo.setFromXrate(entity.getFromXrate());
        eo.setExchangeTranCodet(entity.getExchangeTranCodet());
        eo.setToCcy(Ccy.byValue(entity.getToCcy()));
        eo.setOthBankName(entity.getOthBankName());
        eo.setInternalKey(entity.getInternalKey());
        eo.setOthSeqNo(entity.getOthSeqNo());
        eo.setOthRealTranAddr(entity.getOthRealTranAddr());
        eo.setAmtType(IntCalcAmtType.byValue(entity.getAmtType()));
        eo.setClientType(ClientType.byValue(entity.getClientType()));
        eo.setAutoTradeFlag(entity.getAutoTradeFlag());
        eo.setUserId(entity.getUserId());
        eo.setAcctDesc(entity.getAcctDesc());
        eo.setOthRealDocumentId(entity.getOthRealDocumentId());
        eo.setAcctTranFlag(AcctTranFlag.byValue(entity.getAcctTranFlag()));
        eo.setAmtCalcType(AmtCalcType.byValue(entity.getAmtCalcType()));
        eo.setOthRealBankCode(entity.getOthRealBankCode());
        eo.setLcyTranAmt(entity.getLcyTranAmt());
        eo.setOthAcctCcy(AcctCcy.byValue(entity.getOthAcctCcy()));
        eo.setSendSystem(entity.getSendSystem());
        eo.setOthProdNo(entity.getOthProdNo());
        eo.setTackOverCcyRateOne(entity.getTackOverCcyRateOne());
        eo.setOthAcctSeqNo(entity.getOthAcctSeqNo());
        eo.setAccountingStatus(AccountingStatus.byValue(entity.getAccountingStatus()));
        eo.setSubSeqNo(entity.getSubSeqNo());
        eo.setOthTranAddr(entity.getOthTranAddr());
        eo.setNarrativeCode(entity.getNarrativeCode());
        eo.setTranDate(entity.getTranDate());
        eo.setBaseEquivAmt(entity.getBaseEquivAmt());
        eo.setCcy(Ccy.byValue(entity.getCcy()));
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setPayUnit(entity.getPayUnit());
        eo.setOthRealBankName(entity.getOthRealBankName());
        eo.setRemainTerm(RemainTerm.byValue(entity.getRemainTerm()));
        eo.setFromCcy(Ccy.byValue(entity.getFromCcy()));
        eo.setReversalSeqNo(entity.getReversalSeqNo());
        eo.setTranDesc(entity.getTranDesc());
        eo.setMediumType(MediumType.byValue(entity.getMediumType()));
        eo.setCrDrInd(CrDrInd.byValue(entity.getCrDrInd()));
        eo.setToAmount(entity.getToAmount());
        eo.setDocumentId(entity.getDocumentId());
        eo.setTranStatus(TranStatus.byValue(entity.getTranStatus()));
        eo.setDocType(DocType.byValue(entity.getDocType()));
        eo.setWithdrawalType(WithdrawalType.byValue(entity.getWithdrawalType()));
        eo.setOthInternalKey(entity.getOthInternalKey());
        eo.setContraTranDate(entity.getContraTranDate());
        eo.setPriority(entity.getPriority());
        eo.setFlatRate(entity.getFlatRate());
        return eo;
    }

    public static RbBusTranJnl eoToEntity(RbBusTranJnlEO eo) {
        if (eo == null) {
            return null;
        }
        RbBusTranJnl entity = new RbBusTranJnl();
        entity.setCommissionClientTel(eo.getCommissionClientTel());
        entity.setReversalDate(eo.getReversalDate());
        entity.setReversalTranType(eo.getReversalTranType() == null ? null : eo.getReversalTranType().getValue());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setFhSeqNo(eo.getFhSeqNo());
        entity.setOrigSystem(eo.getOrigSystem() == null ? null : eo.getOrigSystem().getValue());
        entity.setOthDocumentId(eo.getOthDocumentId());
        entity.setPreviousBalAmt(eo.getPreviousBalAmt());
        entity.setTranCountry(eo.getTranCountry() == null ? null : eo.getTranCountry().getValue());
        entity.setLastUpdTimestamp(eo.getLastUpdTimestamp());
        entity.setTranNote(eo.getTranNote());
        entity.setContraAcctCcy(eo.getContraAcctCcy() == null ? null : eo.getContraAcctCcy().getValue());
        entity.setLimitRefList(eo.getLimitRefList());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setReversalFlag(eo.getReversalFlag());
        entity.setCashFromCode(eo.getCashFromCode());
        entity.setOthReference(eo.getOthReference());
        entity.setOthRealBranchRegionCode(eo.getOthRealBranchRegionCode() == null ? null : eo.getOthRealBranchRegionCode().getValue());
        entity.setTranType(eo.getTranType() == null ? null : eo.getTranType().getValue());
        entity.setOthRealTranName(eo.getOthRealTranName());
        entity.setVoucherNo(eo.getVoucherNo());
        entity.setReaccountCd(eo.getReaccountCd());
        entity.setPrimaryTranSeqNo(eo.getPrimaryTranSeqNo());
        entity.setBaseCcyAmountOne(eo.getBaseCcyAmountOne());
        entity.setMediumFlag(eo.getMediumFlag() == null ? null : eo.getMediumFlag().getValue());
        entity.setOvToAmount(eo.getOvToAmount());
        entity.setFromRateFlag(eo.getFromRateFlag() == null ? null : eo.getFromRateFlag().getValue());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setToRateFlag(eo.getToRateFlag() == null ? null : eo.getToRateFlag().getValue());
        entity.setNarrative(eo.getNarrative());
        entity.setOthRealBaseAcctNo(eo.getOthRealBaseAcctNo());
        entity.setOthAcctDesc(eo.getOthAcctDesc());
        entity.setCommissionClientName(eo.getCommissionClientName());
        entity.setPrintIndicator(eo.getPrintIndicator());
        entity.setIsFinSubAcct(eo.getIsFinSubAcct());
        entity.setActualBal(eo.getActualBal());
        entity.setCrossRate(eo.getCrossRate());
        entity.setEventType(eo.getEventType());
        entity.setContraEquivAmt(eo.getContraEquivAmt());
        entity.setRateType(eo.getRateType() == null ? null : eo.getRateType().getValue());
        entity.setEffectDate(eo.getEffectDate());
        entity.setAcctSetType(eo.getAcctSetType() == null ? null : eo.getAcctSetType().getValue());
        entity.setChannelSeqNo(eo.getChannelSeqNo());
        entity.setApprUserId(eo.getApprUserId());
        entity.setTackOverCcyRateTwo(eo.getTackOverCcyRateTwo());
        entity.setChannel(eo.getChannel() == null ? null : eo.getChannel().getValue());
        entity.setOthDocumentType(eo.getOthDocumentType() == null ? null : eo.getOthDocumentType().getValue());
        entity.setOthRealDocumentType(eo.getOthRealDocumentType() == null ? null : eo.getOthRealDocumentType().getValue());
        entity.setLoanProdNo(eo.getLoanProdNo());
        entity.setToId(eo.getToId() == null ? null : eo.getToId().getValue());
        entity.setCustRate(eo.getCustRate());
        entity.setBalType(eo.getBalType() == null ? null : eo.getBalType().getValue());
        entity.setSubAcctNo(eo.getSubAcctNo());
        entity.setBusSeqNo(eo.getBusSeqNo());
        entity.setAcctStatus(eo.getAcctStatus() == null ? null : eo.getAcctStatus().getValue());
        entity.setRcrRcdInd(eo.getRcrRcdInd() == null ? null : eo.getRcrRcdInd().getValue());
        entity.setExchangeTranCode(eo.getExchangeTranCode());
        entity.setClientName(eo.getClientName());
        entity.setServCharge(eo.getServCharge());
        entity.setAcctSeqNo(eo.getAcctSeqNo());
        entity.setApprIndicator(eo.getApprIndicator() == null ? null : eo.getApprIndicator().getValue());
        entity.setDocumentType(eo.getDocumentType() == null ? null : eo.getDocumentType().getValue());
        entity.setAcctBranch(eo.getAcctBranch() == null ? null : eo.getAcctBranch().getValue());
        entity.setOthTranName(eo.getOthTranName());
        entity.setIsCommTran(eo.getIsCommTran());
        entity.setClientNo(eo.getClientNo());
        entity.setBaseCcyAmountTwo(eo.getBaseCcyAmountTwo());
        entity.setAcctRealFlag(eo.getAcctRealFlag());
        entity.setOthBranchRegionalismCode(eo.getOthBranchRegionalismCode() == null ? null : eo.getOthBranchRegionalismCode().getValue());
        entity.setFromAmount(eo.getFromAmount());
        entity.setSourceModule(eo.getSourceModule() == null ? null : eo.getSourceModule().getValue());
        entity.setToXrate(eo.getToXrate());
        entity.setProfitCenter(eo.getProfitCenter() == null ? null : eo.getProfitCenter().getValue());
        entity.setCashToCountry(eo.getCashToCountry() == null ? null : eo.getCashToCountry().getValue());
        entity.setBankSeqNo(eo.getBankSeqNo());
        entity.setCashToCode(eo.getCashToCode());
        entity.setPrimaryEventType(eo.getPrimaryEventType());
        entity.setTranMethod(eo.getTranMethod() == null ? null : eo.getTranMethod().getValue());
        entity.setLender(eo.getLender());
        entity.setProgramId(eo.getProgramId());
        entity.setCashFromCountry(eo.getCashFromCountry() == null ? null : eo.getCashFromCountry().getValue());
        entity.setOthRealProdNo(eo.getOthRealProdNo());
        entity.setPrintCnt(eo.getPrintCnt());
        entity.setDealCode(eo.getDealCode());
        entity.setProdNo(eo.getProdNo());
        entity.setOthBankCode(eo.getOthBankCode());
        entity.setOthBaseAcctNo(eo.getOthBaseAcctNo());
        entity.setCashItem(eo.getCashItem() == null ? null : eo.getCashItem().getValue());
        entity.setBatchNo(eo.getBatchNo());
        entity.setChannelDate(eo.getChannelDate());
        entity.setBillNo(eo.getBillNo());
        entity.setSeqNo(eo.getSeqNo());
        entity.setReceiptNo(eo.getReceiptNo());
        entity.setOvCrossRate(eo.getOvCrossRate());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setOthBranch(eo.getOthBranch() == null ? null : eo.getOthBranch().getValue());
        entity.setReference(eo.getReference());
        entity.setQuoteType(eo.getQuoteType() == null ? null : eo.getQuoteType().getValue());
        entity.setCashSourceCountry(eo.getCashSourceCountry() == null ? null : eo.getCashSourceCountry().getValue());
        entity.setAutoReversalFlag(eo.getAutoReversalFlag() == null ? null : eo.getAutoReversalFlag().getValue());
        entity.setTranAmt(eo.getTranAmt());
        entity.setGlPostedFlag(eo.getGlPostedFlag());
        entity.setAcctClass(eo.getAcctClass() == null ? null : eo.getAcctClass().getValue());
        entity.setPbkUpdFlag(eo.getPbkUpdFlag());
        entity.setGlNo(eo.getGlNo());
        entity.setActualBalAmtFin(eo.getActualBalAmtFin());
        entity.setTranBranch(eo.getTranBranch() == null ? null : eo.getTranBranch().getValue());
        entity.setPrefix(eo.getPrefix());
        entity.setCashUsePlaceCode(eo.getCashUsePlaceCode() == null ? null : eo.getCashUsePlaceCode().getValue());
        entity.setSettlementDate(eo.getSettlementDate());
        entity.setFromXrate(eo.getFromXrate());
        entity.setExchangeTranCodet(eo.getExchangeTranCodet());
        entity.setToCcy(eo.getToCcy() == null ? null : eo.getToCcy().getValue());
        entity.setOthBankName(eo.getOthBankName());
        entity.setInternalKey(eo.getInternalKey());
        entity.setOthSeqNo(eo.getOthSeqNo());
        entity.setOthRealTranAddr(eo.getOthRealTranAddr());
        entity.setAmtType(eo.getAmtType() == null ? null : eo.getAmtType().getValue());
        entity.setClientType(eo.getClientType() == null ? null : eo.getClientType().getValue());
        entity.setAutoTradeFlag(eo.getAutoTradeFlag());
        entity.setUserId(eo.getUserId());
        entity.setAcctDesc(eo.getAcctDesc());
        entity.setOthRealDocumentId(eo.getOthRealDocumentId());
        entity.setAcctTranFlag(eo.getAcctTranFlag() == null ? null : eo.getAcctTranFlag().getValue());
        entity.setAmtCalcType(eo.getAmtCalcType() == null ? null : eo.getAmtCalcType().getValue());
        entity.setOthRealBankCode(eo.getOthRealBankCode());
        entity.setLcyTranAmt(eo.getLcyTranAmt());
        entity.setOthAcctCcy(eo.getOthAcctCcy() == null ? null : eo.getOthAcctCcy().getValue());
        entity.setSendSystem(eo.getSendSystem());
        entity.setOthProdNo(eo.getOthProdNo());
        entity.setTackOverCcyRateOne(eo.getTackOverCcyRateOne());
        entity.setOthAcctSeqNo(eo.getOthAcctSeqNo());
        entity.setAccountingStatus(eo.getAccountingStatus() == null ? null : eo.getAccountingStatus().getValue());
        entity.setSubSeqNo(eo.getSubSeqNo());
        entity.setOthTranAddr(eo.getOthTranAddr());
        entity.setNarrativeCode(eo.getNarrativeCode());
        entity.setTranDate(eo.getTranDate());
        entity.setBaseEquivAmt(eo.getBaseEquivAmt());
        entity.setCcy(eo.getCcy() == null ? null : eo.getCcy().getValue());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setPayUnit(eo.getPayUnit());
        entity.setOthRealBankName(eo.getOthRealBankName());
        entity.setRemainTerm(eo.getRemainTerm() == null ? null : eo.getRemainTerm().getValue());
        entity.setFromCcy(eo.getFromCcy() == null ? null : eo.getFromCcy().getValue());
        entity.setReversalSeqNo(eo.getReversalSeqNo());
        entity.setTranDesc(eo.getTranDesc());
        entity.setMediumType(eo.getMediumType() == null ? null : eo.getMediumType().getValue());
        entity.setCrDrInd(eo.getCrDrInd() == null ? null : eo.getCrDrInd().getValue());
        entity.setToAmount(eo.getToAmount());
        entity.setDocumentId(eo.getDocumentId());
        entity.setTranStatus(eo.getTranStatus() == null ? null : eo.getTranStatus().getValue());
        entity.setDocType(eo.getDocType() == null ? null : eo.getDocType().getValue());
        entity.setWithdrawalType(eo.getWithdrawalType() == null ? null : eo.getWithdrawalType().getValue());
        entity.setOthInternalKey(eo.getOthInternalKey());
        entity.setContraTranDate(eo.getContraTranDate());
        entity.setPriority(eo.getPriority());
        entity.setFlatRate(eo.getFlatRate());
        return entity;
    }

    public static RbBusTranJnlExample eoToEntityExample(RbBusTranJnlEO eo) {
        if (eo == null) {
            return null;
        }
        RbBusTranJnlExample example = new RbBusTranJnlExample();
        RbBusTranJnlExample.Criteria criteria = example.createCriteria();
        if (eo.getCommissionClientTel() != null) criteria.andCommissionClientTelEqualTo(eo.getCommissionClientTel());
        if (eo.getReversalDate() != null) criteria.andReversalDateEqualTo(eo.getReversalDate());
        if (eo.getReversalTranType() != null) criteria.andReversalTranTypeEqualTo(eo.getReversalTranType().getValue());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getFhSeqNo() != null) criteria.andFhSeqNoEqualTo(eo.getFhSeqNo());
        if (eo.getOrigSystem() != null) criteria.andOrigSystemEqualTo(eo.getOrigSystem().getValue());
        if (eo.getOthDocumentId() != null) criteria.andOthDocumentIdEqualTo(eo.getOthDocumentId());
        if (eo.getPreviousBalAmt() != null) criteria.andPreviousBalAmtEqualTo(eo.getPreviousBalAmt());
        if (eo.getTranCountry() != null) criteria.andTranCountryEqualTo(eo.getTranCountry().getValue());
        if (eo.getLastUpdTimestamp() != null) criteria.andLastUpdTimestampEqualTo(eo.getLastUpdTimestamp());
        if (eo.getTranNote() != null) criteria.andTranNoteEqualTo(eo.getTranNote());
        if (eo.getContraAcctCcy() != null) criteria.andContraAcctCcyEqualTo(eo.getContraAcctCcy().getValue());
        if (eo.getLimitRefList() != null) criteria.andLimitRefListEqualTo(eo.getLimitRefList());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getReversalFlag() != null) criteria.andReversalFlagEqualTo(eo.getReversalFlag());
        if (eo.getCashFromCode() != null) criteria.andCashFromCodeEqualTo(eo.getCashFromCode());
        if (eo.getOthReference() != null) criteria.andOthReferenceEqualTo(eo.getOthReference());
        if (eo.getOthRealBranchRegionCode() != null) criteria.andOthRealBranchRegionCodeEqualTo(eo.getOthRealBranchRegionCode().getValue());
        if (eo.getTranType() != null) criteria.andTranTypeEqualTo(eo.getTranType().getValue());
        if (eo.getOthRealTranName() != null) criteria.andOthRealTranNameEqualTo(eo.getOthRealTranName());
        if (eo.getVoucherNo() != null) criteria.andVoucherNoEqualTo(eo.getVoucherNo());
        if (eo.getReaccountCd() != null) criteria.andReaccountCdEqualTo(eo.getReaccountCd());
        if (eo.getPrimaryTranSeqNo() != null) criteria.andPrimaryTranSeqNoEqualTo(eo.getPrimaryTranSeqNo());
        if (eo.getBaseCcyAmountOne() != null) criteria.andBaseCcyAmountOneEqualTo(eo.getBaseCcyAmountOne());
        if (eo.getMediumFlag() != null) criteria.andMediumFlagEqualTo(eo.getMediumFlag().getValue());
        if (eo.getOvToAmount() != null) criteria.andOvToAmountEqualTo(eo.getOvToAmount());
        if (eo.getFromRateFlag() != null) criteria.andFromRateFlagEqualTo(eo.getFromRateFlag().getValue());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getToRateFlag() != null) criteria.andToRateFlagEqualTo(eo.getToRateFlag().getValue());
        if (eo.getNarrative() != null) criteria.andNarrativeEqualTo(eo.getNarrative());
        if (eo.getOthRealBaseAcctNo() != null) criteria.andOthRealBaseAcctNoEqualTo(eo.getOthRealBaseAcctNo());
        if (eo.getOthAcctDesc() != null) criteria.andOthAcctDescEqualTo(eo.getOthAcctDesc());
        if (eo.getCommissionClientName() != null) criteria.andCommissionClientNameEqualTo(eo.getCommissionClientName());
        if (eo.getPrintIndicator() != null) criteria.andPrintIndicatorEqualTo(eo.getPrintIndicator());
        if (eo.getIsFinSubAcct() != null) criteria.andIsFinSubAcctEqualTo(eo.getIsFinSubAcct());
        if (eo.getActualBal() != null) criteria.andActualBalEqualTo(eo.getActualBal());
        if (eo.getCrossRate() != null) criteria.andCrossRateEqualTo(eo.getCrossRate());
        if (eo.getEventType() != null) criteria.andEventTypeEqualTo(eo.getEventType());
        if (eo.getContraEquivAmt() != null) criteria.andContraEquivAmtEqualTo(eo.getContraEquivAmt());
        if (eo.getRateType() != null) criteria.andRateTypeEqualTo(eo.getRateType().getValue());
        if (eo.getEffectDate() != null) criteria.andEffectDateEqualTo(eo.getEffectDate());
        if (eo.getAcctSetType() != null) criteria.andAcctSetTypeEqualTo(eo.getAcctSetType().getValue());
        if (eo.getChannelSeqNo() != null) criteria.andChannelSeqNoEqualTo(eo.getChannelSeqNo());
        if (eo.getApprUserId() != null) criteria.andApprUserIdEqualTo(eo.getApprUserId());
        if (eo.getTackOverCcyRateTwo() != null) criteria.andTackOverCcyRateTwoEqualTo(eo.getTackOverCcyRateTwo());
        if (eo.getChannel() != null) criteria.andChannelEqualTo(eo.getChannel().getValue());
        if (eo.getOthDocumentType() != null) criteria.andOthDocumentTypeEqualTo(eo.getOthDocumentType().getValue());
        if (eo.getOthRealDocumentType() != null) criteria.andOthRealDocumentTypeEqualTo(eo.getOthRealDocumentType().getValue());
        if (eo.getLoanProdNo() != null) criteria.andLoanProdNoEqualTo(eo.getLoanProdNo());
        if (eo.getToId() != null) criteria.andToIdEqualTo(eo.getToId().getValue());
        if (eo.getCustRate() != null) criteria.andCustRateEqualTo(eo.getCustRate());
        if (eo.getBalType() != null) criteria.andBalTypeEqualTo(eo.getBalType().getValue());
        if (eo.getSubAcctNo() != null) criteria.andSubAcctNoEqualTo(eo.getSubAcctNo());
        if (eo.getBusSeqNo() != null) criteria.andBusSeqNoEqualTo(eo.getBusSeqNo());
        if (eo.getAcctStatus() != null) criteria.andAcctStatusEqualTo(eo.getAcctStatus().getValue());
        if (eo.getRcrRcdInd() != null) criteria.andRcrRcdIndEqualTo(eo.getRcrRcdInd().getValue());
        if (eo.getExchangeTranCode() != null) criteria.andExchangeTranCodeEqualTo(eo.getExchangeTranCode());
        if (eo.getClientName() != null) criteria.andClientNameEqualTo(eo.getClientName());
        if (eo.getServCharge() != null) criteria.andServChargeEqualTo(eo.getServCharge());
        if (eo.getAcctSeqNo() != null) criteria.andAcctSeqNoEqualTo(eo.getAcctSeqNo());
        if (eo.getApprIndicator() != null) criteria.andApprIndicatorEqualTo(eo.getApprIndicator().getValue());
        if (eo.getDocumentType() != null) criteria.andDocumentTypeEqualTo(eo.getDocumentType().getValue());
        if (eo.getAcctBranch() != null) criteria.andAcctBranchEqualTo(eo.getAcctBranch().getValue());
        if (eo.getOthTranName() != null) criteria.andOthTranNameEqualTo(eo.getOthTranName());
        if (eo.getIsCommTran() != null) criteria.andIsCommTranEqualTo(eo.getIsCommTran());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getBaseCcyAmountTwo() != null) criteria.andBaseCcyAmountTwoEqualTo(eo.getBaseCcyAmountTwo());
        if (eo.getAcctRealFlag() != null) criteria.andAcctRealFlagEqualTo(eo.getAcctRealFlag());
        if (eo.getOthBranchRegionalismCode() != null) criteria.andOthBranchRegionalismCodeEqualTo(eo.getOthBranchRegionalismCode().getValue());
        if (eo.getFromAmount() != null) criteria.andFromAmountEqualTo(eo.getFromAmount());
        if (eo.getSourceModule() != null) criteria.andSourceModuleEqualTo(eo.getSourceModule().getValue());
        if (eo.getToXrate() != null) criteria.andToXrateEqualTo(eo.getToXrate());
        if (eo.getProfitCenter() != null) criteria.andProfitCenterEqualTo(eo.getProfitCenter().getValue());
        if (eo.getCashToCountry() != null) criteria.andCashToCountryEqualTo(eo.getCashToCountry().getValue());
        if (eo.getBankSeqNo() != null) criteria.andBankSeqNoEqualTo(eo.getBankSeqNo());
        if (eo.getCashToCode() != null) criteria.andCashToCodeEqualTo(eo.getCashToCode());
        if (eo.getPrimaryEventType() != null) criteria.andPrimaryEventTypeEqualTo(eo.getPrimaryEventType());
        if (eo.getTranMethod() != null) criteria.andTranMethodEqualTo(eo.getTranMethod().getValue());
        if (eo.getLender() != null) criteria.andLenderEqualTo(eo.getLender());
        if (eo.getProgramId() != null) criteria.andProgramIdEqualTo(eo.getProgramId());
        if (eo.getCashFromCountry() != null) criteria.andCashFromCountryEqualTo(eo.getCashFromCountry().getValue());
        if (eo.getOthRealProdNo() != null) criteria.andOthRealProdNoEqualTo(eo.getOthRealProdNo());
        if (eo.getPrintCnt() != null) criteria.andPrintCntEqualTo(eo.getPrintCnt());
        if (eo.getDealCode() != null) criteria.andDealCodeEqualTo(eo.getDealCode());
        if (eo.getProdNo() != null) criteria.andProdNoEqualTo(eo.getProdNo());
        if (eo.getOthBankCode() != null) criteria.andOthBankCodeEqualTo(eo.getOthBankCode());
        if (eo.getOthBaseAcctNo() != null) criteria.andOthBaseAcctNoEqualTo(eo.getOthBaseAcctNo());
        if (eo.getCashItem() != null) criteria.andCashItemEqualTo(eo.getCashItem().getValue());
        if (eo.getBatchNo() != null) criteria.andBatchNoEqualTo(eo.getBatchNo());
        if (eo.getChannelDate() != null) criteria.andChannelDateEqualTo(eo.getChannelDate());
        if (eo.getBillNo() != null) criteria.andBillNoEqualTo(eo.getBillNo());
        if (eo.getSeqNo() != null) criteria.andSeqNoEqualTo(eo.getSeqNo());
        if (eo.getReceiptNo() != null) criteria.andReceiptNoEqualTo(eo.getReceiptNo());
        if (eo.getOvCrossRate() != null) criteria.andOvCrossRateEqualTo(eo.getOvCrossRate());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getOthBranch() != null) criteria.andOthBranchEqualTo(eo.getOthBranch().getValue());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getQuoteType() != null) criteria.andQuoteTypeEqualTo(eo.getQuoteType().getValue());
        if (eo.getCashSourceCountry() != null) criteria.andCashSourceCountryEqualTo(eo.getCashSourceCountry().getValue());
        if (eo.getAutoReversalFlag() != null) criteria.andAutoReversalFlagEqualTo(eo.getAutoReversalFlag().getValue());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getGlPostedFlag() != null) criteria.andGlPostedFlagEqualTo(eo.getGlPostedFlag());
        if (eo.getAcctClass() != null) criteria.andAcctClassEqualTo(eo.getAcctClass().getValue());
        if (eo.getPbkUpdFlag() != null) criteria.andPbkUpdFlagEqualTo(eo.getPbkUpdFlag());
        if (eo.getGlNo() != null) criteria.andGlNoEqualTo(eo.getGlNo());
        if (eo.getActualBalAmtFin() != null) criteria.andActualBalAmtFinEqualTo(eo.getActualBalAmtFin());
        if (eo.getTranBranch() != null) criteria.andTranBranchEqualTo(eo.getTranBranch().getValue());
        if (eo.getPrefix() != null) criteria.andPrefixEqualTo(eo.getPrefix());
        if (eo.getCashUsePlaceCode() != null) criteria.andCashUsePlaceCodeEqualTo(eo.getCashUsePlaceCode().getValue());
        if (eo.getSettlementDate() != null) criteria.andSettlementDateEqualTo(eo.getSettlementDate());
        if (eo.getFromXrate() != null) criteria.andFromXrateEqualTo(eo.getFromXrate());
        if (eo.getExchangeTranCodet() != null) criteria.andExchangeTranCodetEqualTo(eo.getExchangeTranCodet());
        if (eo.getToCcy() != null) criteria.andToCcyEqualTo(eo.getToCcy().getValue());
        if (eo.getOthBankName() != null) criteria.andOthBankNameEqualTo(eo.getOthBankName());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getOthSeqNo() != null) criteria.andOthSeqNoEqualTo(eo.getOthSeqNo());
        if (eo.getOthRealTranAddr() != null) criteria.andOthRealTranAddrEqualTo(eo.getOthRealTranAddr());
        if (eo.getAmtType() != null) criteria.andAmtTypeEqualTo(eo.getAmtType().getValue());
        if (eo.getClientType() != null) criteria.andClientTypeEqualTo(eo.getClientType().getValue());
        if (eo.getAutoTradeFlag() != null) criteria.andAutoTradeFlagEqualTo(eo.getAutoTradeFlag());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getAcctDesc() != null) criteria.andAcctDescEqualTo(eo.getAcctDesc());
        if (eo.getOthRealDocumentId() != null) criteria.andOthRealDocumentIdEqualTo(eo.getOthRealDocumentId());
        if (eo.getAcctTranFlag() != null) criteria.andAcctTranFlagEqualTo(eo.getAcctTranFlag().getValue());
        if (eo.getAmtCalcType() != null) criteria.andAmtCalcTypeEqualTo(eo.getAmtCalcType().getValue());
        if (eo.getOthRealBankCode() != null) criteria.andOthRealBankCodeEqualTo(eo.getOthRealBankCode());
        if (eo.getLcyTranAmt() != null) criteria.andLcyTranAmtEqualTo(eo.getLcyTranAmt());
        if (eo.getOthAcctCcy() != null) criteria.andOthAcctCcyEqualTo(eo.getOthAcctCcy().getValue());
        if (eo.getSendSystem() != null) criteria.andSendSystemEqualTo(eo.getSendSystem());
        if (eo.getOthProdNo() != null) criteria.andOthProdNoEqualTo(eo.getOthProdNo());
        if (eo.getTackOverCcyRateOne() != null) criteria.andTackOverCcyRateOneEqualTo(eo.getTackOverCcyRateOne());
        if (eo.getOthAcctSeqNo() != null) criteria.andOthAcctSeqNoEqualTo(eo.getOthAcctSeqNo());
        if (eo.getAccountingStatus() != null) criteria.andAccountingStatusEqualTo(eo.getAccountingStatus().getValue());
        if (eo.getSubSeqNo() != null) criteria.andSubSeqNoEqualTo(eo.getSubSeqNo());
        if (eo.getOthTranAddr() != null) criteria.andOthTranAddrEqualTo(eo.getOthTranAddr());
        if (eo.getNarrativeCode() != null) criteria.andNarrativeCodeEqualTo(eo.getNarrativeCode());
        if (eo.getTranDate() != null) criteria.andTranDateEqualTo(eo.getTranDate());
        if (eo.getBaseEquivAmt() != null) criteria.andBaseEquivAmtEqualTo(eo.getBaseEquivAmt());
        if (eo.getCcy() != null) criteria.andCcyEqualTo(eo.getCcy().getValue());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getPayUnit() != null) criteria.andPayUnitEqualTo(eo.getPayUnit());
        if (eo.getOthRealBankName() != null) criteria.andOthRealBankNameEqualTo(eo.getOthRealBankName());
        if (eo.getRemainTerm() != null) criteria.andRemainTermEqualTo(eo.getRemainTerm().getValue());
        if (eo.getFromCcy() != null) criteria.andFromCcyEqualTo(eo.getFromCcy().getValue());
        if (eo.getReversalSeqNo() != null) criteria.andReversalSeqNoEqualTo(eo.getReversalSeqNo());
        if (eo.getTranDesc() != null) criteria.andTranDescEqualTo(eo.getTranDesc());
        if (eo.getMediumType() != null) criteria.andMediumTypeEqualTo(eo.getMediumType().getValue());
        if (eo.getCrDrInd() != null) criteria.andCrDrIndEqualTo(eo.getCrDrInd().getValue());
        if (eo.getToAmount() != null) criteria.andToAmountEqualTo(eo.getToAmount());
        if (eo.getDocumentId() != null) criteria.andDocumentIdEqualTo(eo.getDocumentId());
        if (eo.getTranStatus() != null) criteria.andTranStatusEqualTo(eo.getTranStatus().getValue());
        if (eo.getDocType() != null) criteria.andDocTypeEqualTo(eo.getDocType().getValue());
        if (eo.getWithdrawalType() != null) criteria.andWithdrawalTypeEqualTo(eo.getWithdrawalType().getValue());
        if (eo.getOthInternalKey() != null) criteria.andOthInternalKeyEqualTo(eo.getOthInternalKey());
        if (eo.getContraTranDate() != null) criteria.andContraTranDateEqualTo(eo.getContraTranDate());
        if (eo.getPriority() != null) criteria.andPriorityEqualTo(eo.getPriority());
        if (eo.getFlatRate() != null) criteria.andFlatRateEqualTo(eo.getFlatRate());
        return example;
    }
}